### ISSUE TITLE
Get docker hub to build minion

### ISSUE THREAD

**Issue by andymckay** [mozilla/minion-vm#3]
Push builds to docker hub for faster setups. Unfortunately I'm not sure how to build more than one docker image from one repo at this point.

**Comment by ygjb** [comment]
we could create repos that contain the appropriate configs to generate docker images for each of the components?

**Comment by andymckay** [comment]
I had a pull request for a Dockerfile in each repo (eg. minion-frontend), until I found this repo. Wasn't sure which way people wanted to go. Pulling down repos from docker hub has been shown to be a huge win for us in the past, I'd recommend it.

**Comment by april** [comment]
If we can get it to work, then by all means go for it.  I mostly created this repo because I was the sole developer and this was what I had been working on to get Minion working for me in VM.

By and large, Minion is far easier to hack on in Vagrant than Docker, because it requires so many separate components.  For production deployment, I think getting solid docker hub images would be phenomenal.
